import { createServer } from 'vite';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
const server = await createServer({ server: { host: '127.0.0.1', port: 0 }, logLevel: 'silent' });
await server.listen();
const launch = { headless: true };
if (process.env.CHROMIUM_PATH) launch.executablePath = process.env.CHROMIUM_PATH;
if (process.env.CHROMIUM_ARGS) launch.args = JSON.parse(process.env.CHROMIUM_ARGS);
const browser = await chromium.launch(launch);
const failures = [];
try {
  await mkdir('docs/capturas', { recursive: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.on('pageerror', e => failures.push(e.message));
  page.on('dialog', dialog => dialog.accept());
  const base = `http://127.0.0.1:${server.httpServer.address().port}`;
  await page.goto(`${base}/?demo=1`);
  await page.getByRole('heading', { name: 'Tu negocio, a tu manera.' }).waitFor();
  await page.screenshot({ path: 'docs/capturas/inicio-escritorio.png', fullPage: true });
  const before = await page.evaluate(() => window.storage.getSnapshot());
  await page.getByRole('button', { name: 'Nueva venta', exact: true }).first().click();
  await page.getByRole('button', { name: /Caja de alfajores/ }).click();
  await page.getByRole('button', { name: 'Registrar venta', exact: true }).click();
  await page.getByText('Venta lista ·', { exact: false }).waitFor();
  const after = await page.evaluate(() => window.storage.getSnapshot());
  assert.equal(after.sales.length, before.sales.length + 1);
  assert.equal(after.products[0].stock, before.products[0].stock - 1);
  assert.equal(after.movements.length, before.movements.length + 1);
  console.log('PASS venta e inventario en una operación');
  await page.getByRole('button', { name: 'Finanzas', exact: true }).first().click();
  await page.getByRole('button', { name: 'Gastos', exact: true }).click();
  await page.getByRole('button', { name: 'Comprar insumos', exact: true }).click();
  await page.getByLabel('Cantidad comprada', { exact: true }).fill('2');
  await page.getByLabel('Unidad de compra', { exact: true }).selectOption('unid');
  await page.getByLabel('Total pagado', { exact: true }).fill('600');
  await page.getByRole('button', { name: 'Agregar otro insumo', exact: true }).click();
  await page.getByLabel('Cantidad comprada', { exact: true }).nth(1).fill('3');
  await page.getByLabel('Unidad de compra', { exact: true }).nth(1).selectOption('unid');
  await page.getByLabel('Total pagado', { exact: true }).nth(1).fill('900');
  await page.getByRole('button', { name: 'Guardar compra y reponer stock' }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  const bought = await page.evaluate(() => window.storage.getSnapshot());
  assert.equal(bought.insumos[0].stock, before.insumos[0].stock + 5);
  assert.equal(bought.expenses.length, before.expenses.length + 1);
  assert.equal(bought.expenses.find(e => !before.expenses.some(old => old.id === e.id)).total, 1500);
  console.log('PASS compra con dos líneas del mismo insumo');
  await page.getByRole('button', { name: 'Registrar gasto', exact: true }).click();
  await page.getByLabel('Descripción', { exact: true }).fill('Arriendo pendiente QA');
  await page.getByLabel('Total', { exact: true }).fill('5000');
  await page.getByLabel('Estado', { exact: true }).selectOption('Pendiente');
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Marcar pagado', exact: true }).click();
  await page.waitForFunction(async () => (await window.storage.getSnapshot()).expenses.some(e => e.description === 'Arriendo pendiente QA' && e.paidAt));
  console.log('PASS gasto pendiente y pago posterior');
  await page.getByRole('button', { name: 'Registrar gasto', exact: true }).click();
  await page.getByLabel('Descripción', { exact: true }).fill('Error simulado');
  await page.getByLabel('Total', { exact: true }).fill('20');
  await page.evaluate(() => { window.storage.setMany = async () => { throw new Error('Fallo simulado de guardado'); }; });
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByText('Fallo simulado de guardado', { exact: false }).first().waitFor();
  assert.equal(await page.getByRole('dialog').count(), 1);
  assert.equal(await page.getByLabel('Descripción', { exact: true }).inputValue(), 'Error simulado');
  console.log('PASS error de guardado conserva formulario');
  await page.reload();
  await page.getByRole('combobox', { name: 'Negocio de demostración' }).selectOption('demo-tienda');
  await page.waitForFunction(() => window.businessContext?.id === 'demo-tienda');
  const separate = await page.evaluate(() => window.storage.getSnapshot());
  assert.equal(separate.sales.length, 12); assert.equal(separate.profile.currency, 'PEN');
  console.log('PASS separación de negocios y moneda');
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true });
  mobile.on('pageerror', e => failures.push(e.message));
  await mobile.goto(`${base}/?demo=1`);
  await mobile.getByRole('navigation', { name: 'Navegación móvil' }).getByRole('button', { name: 'Inicio', exact: true }).click();
  await mobile.getByRole('heading', { name: 'Tu negocio, a tu manera.' }).waitFor();
  assert(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await mobile.screenshot({ path: 'docs/capturas/inicio-movil.png', fullPage: true });
  await mobile.getByRole('button', { name: 'Venta', exact: true }).click();
  await mobile.getByPlaceholder('Buscar producto').waitFor();
  console.log('PASS navegación móvil sin desbordamiento horizontal');
  const standalone = await browser.newPage();
  standalone.on('pageerror', e => failures.push(e.message));
  const requests=[]; standalone.on('request', r => { if (/^https?:/.test(r.url())) requests.push(r.url()); });
  await standalone.goto(pathToFileURL(`${process.cwd()}/ABRIR_DEMO.html`).href);
  await standalone.getByRole('button', { name: 'Inicio', exact: true }).first().click();
  await standalone.getByRole('heading', { name: 'Tu negocio, a tu manera.' }).waitFor();
  assert.equal(requests.length, 0);
  assert.deepEqual(failures, []);
  console.log('PASS demo autónoma sin solicitudes a Internet; sin errores JavaScript');
} finally { await browser.close(); await server.close(); }
