import React,{useMemo,useState} from 'react';
import {ArrowRight,ArrowUpRight,Plus,ShoppingBag,Wallet,TrendingUp,Clock3,Package,Users,FileText,Boxes,Sparkles,Target,Check,Truck,SlidersHorizontal,BarChart3,ArrowDownRight} from 'lucide-react';
import {analyzeBusiness,summarize,periodRange,shiftDay} from '../domain/intelligence.js';
import {SHORTCUTS,WIDGETS,normalizeAppearance} from '../domain/appearance.js';
const icons={venta:Plus,gasto:Wallet,catalogo:Package,clientes:Users,cotizaciones:FileText,inventario:Boxes,informes:BarChart3,asesor:Sparkles};
const valid=s=>!s.cancelledAt&&!['Cancelado','Anulado'].includes(s.orderStatus);
export default function CommandCenter({data,settings,money,goTo,onPersonalize}){
 const [period,setPeriod]=useState('month'),a=useMemo(()=>analyzeBusiness(data),[data]),ui=normalizeAppearance(settings),today=a.asOf,m=useMemo(()=>summarize(data,periodRange(period,today)),[data,period,today]);
 const points=useMemo(()=>Array.from({length:7},(_,i)=>{const date=shiftDay(today,i-6);return {date,label:new Date(`${date}T12:00:00Z`).toLocaleDateString('es-CL',{weekday:'short',timeZone:'UTC'}),value:summarize(data,{from:date,to:date}).revenue};}),[data,today]);
 const totalWeek=points.reduce((n,p)=>n+p.value,0),max=Math.max(...points.map(p=>p.value),1),best=points.reduce((a,b)=>b.value>a.value?b:a,points[0]);
 const pending=data.sales.filter(s=>valid(s)&&s.orderStatus!=='Entregado').sort((a,b)=>(a.deliveryDate||'9999').localeCompare(b.deliveryDate||'9999'));
 const overdue=pending.filter(s=>s.deliveryDate&&s.deliveryDate<today).length,todayCount=pending.filter(s=>s.deliveryDate===today).length;
 const progress=a.goal.target>0?Math.min(100,a.goal.current/a.goal.target*100):0;
 const priorities=a.alerts.filter(x=>x.severity!=='info').slice(0,3);
 const cards={
 activity:<section className="command-card activity-card"><div className="command-card-heading"><div><span className="ce-eyebrow">EL RITMO DE TU NEGOCIO</span><h3>Tu movimiento</h3></div><span className="command-tag">Últimos 7 días</span></div><div className="activity-total"><strong>{money(totalWeek)}</strong><span>en ventas registradas</span></div><div className="command-bar-chart" role="img" aria-label={`Ventas de los últimos siete días: ${points.map(p=>`${p.date}: ${money(p.value)}`).join(', ')}`}><div className="command-grid-lines" aria-hidden="true"><i/><i/><i/></div>{points.map(p=><div className={`command-bar-column ${p.date===best.date&&p.value>0?'best':''}`} key={p.date}><div className="command-bar-space"><div className="command-bar" style={{height:p.value>0?`${Math.max(3,p.value/max*100)}%`:'2px'}}><span>{money(p.value)}</span></div></div><small>{p.label}</small></div>)}</div><div className="command-card-bottom"><span>{totalWeek>0?`Mayor venta diaria: ${best.label}`:'Aquí aparecerán tus ventas de los últimos siete días.'}</span><button onClick={()=>goTo('informes')}>Ver informe <ArrowUpRight size={15}/></button></div></section>,
 agenda:<section className="command-card agenda-card"><div className="command-card-heading"><div><span className="ce-eyebrow">DA EL SIGUIENTE PASO</span><h3>Tu próxima entrega</h3></div><span className="command-icon lavender"><Truck size={19}/></span></div><div className="command-agenda-summary"><span><strong>{todayCount}</strong> para hoy</span><span className={overdue?'needs-attention':''}><strong>{overdue}</strong> {overdue===1?'atrasada':'atrasadas'}</span></div><div className="command-orders">{pending.slice(0,3).map((s,i)=><button onClick={()=>goTo('pedidos')} key={s.id}><span className={`command-avatar avatar-${i}`}>{(s.customerName||'Venta')[0]}</span><span><strong>{s.customerName||'Venta sin cliente'}</strong><small>{s.deliveryDate===today?'Hoy':s.deliveryDate?new Date(s.deliveryDate+'T12:00:00Z').toLocaleDateString('es-CL',{day:'numeric',month:'short',timeZone:'UTC'}):'Sin fecha definida'} · {s.orderStatus}</small></span><ArrowUpRight size={16}/></button>)}{!pending.length&&<div className="command-empty"><Check size={24}/><strong>Todo entregado</strong><p>No tienes entregas pendientes.</p></div>}</div><div className="command-card-bottom"><span>{pending.length} {pending.length===1?'pedido por entregar':'pedidos por entregar'}</span><button onClick={()=>goTo('pedidos')}>Ver pedidos <ArrowUpRight size={15}/></button></div></section>,
 insights:<section className="command-card insights-card"><div className="command-card-heading"><div><span className="ce-eyebrow">CLARIDAD PARA ACTUAR</span><h3>Tu siguiente decisión</h3></div><Sparkles size={22}/></div><p className="command-subtle">Prioridades para hoy, según tus registros.</p><div className="command-priorities">{priorities.map((p,i)=><button key={p.id} onClick={()=>goTo(p.target)}><span className={`priority-dot ${p.severity}`}/><span><strong>{p.title}</strong><small>{p.action}</small></span><ArrowUpRight size={16}/></button>)}{!priorities.length&&<div className="command-empty"><Check size={24}/><strong>Sin prioridades detectadas</strong><p>Agrega ventas y gastos para recibir sugerencias.</p></div>}</div><button className="command-advisor-link" onClick={()=>goTo('asesor')}>Conversar con mi asesor <ArrowRight size={17}/></button></section>,
 goal:<section className="command-card command-goal"><div className="command-card-heading"><div><span className="ce-eyebrow">EL HORIZONTE LO ELIGES TÚ</span><h3>Tu objetivo del mes</h3></div><Target size={21}/></div><div className="command-goal-content"><div className="command-goal-ring" role="progressbar" aria-label="Avance de la meta mensual" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(progress)} style={{'--progress':`${progress*3.6}deg`}}><div><strong>{a.goal.target>0?`${Math.round(progress)}%`:'—'}</strong><span>{a.goal.target?'de tu meta':'Tu próximo paso'}</span></div></div><div>{a.goal.target>0?<><strong>{money(a.goal.current)}</strong><p>de {money(a.goal.target)} en ventas</p><small>{a.goal.remaining?`Faltan ${money(a.goal.remaining)} para llegar.`:'¡Meta alcanzada! Sigue a tu ritmo.'}</small></>:<><strong>Haz espacio para crecer.</strong><p>Define cuánto quieres vender y sigue tu avance.</p></>}</div></div><div className="command-card-bottom"><span>{a.goal.target>0?`${a.goal.daysLeft} días restantes, incluido hoy`:'Cada negocio tiene su propio ritmo.'}</span><button onClick={()=>goTo('preferencias')}>{a.goal.target>0?'Ajustar mi meta':'Definir mi meta'} <ArrowUpRight size={15}/></button></div></section>
 };
 return <div className="command-center"><section className="command-welcome"><div className="command-welcome-copy"><span className="command-kicker"><i/>ESTÁS AL FRENTE</span><h3>Tu próxima gran decisión<br/><em>empieza aquí.</em></h3><p>{ui.workspaceMotto||'Cada decisión cuenta. Este es tu espacio para avanzar.'}</p><button onClick={()=>goTo('venta')} className="command-primary"><Plus size={18}/> Nueva venta <ArrowUpRight size={17}/></button></div><div className="command-orbit" aria-hidden="true"><span className="orbit-ring r1"/><span className="orbit-ring r2"/><span className="orbit-ring r3"/><i className="orbit-point p1"/><i className="orbit-point p2"/><span className="orbit-center"><TrendingUp size={36}/></span><span className="orbit-label">TU VISIÓN<br/><strong>EN MOVIMIENTO</strong></span></div><button className="command-customize" onClick={onPersonalize}><SlidersHorizontal size={15}/> Hazlo tuyo</button></section>
 <section className="home-section home-summary" aria-labelledby="home-summary-title"><div className="command-numbers-heading"><div><span className="ce-eyebrow">01 · RESUMEN DEL NEGOCIO</span><h3 id="home-summary-title">Tus números, sin vueltas.</h3></div><div className="command-periods" role="group" aria-label="Período del resumen">{[['day','Hoy'],['week','7 días'],['month','Este mes']].map(([id,label])=><button key={id} aria-pressed={period===id} onClick={()=>setPeriod(id)}>{label}</button>)}</div></div>
 <div className="command-metrics">{[[ShoppingBag,'Ventas registradas',m.revenue,`${m.count} ${m.count===1?'venta registrada':'ventas registradas'} en el período`,'mint'],[Wallet,'Dinero cobrado',m.collected,'Pagos recibidos en el período','blue'],[Clock3,'Por cobrar',a.current.receivables,'Saldo total pendiente','peach'],[TrendingUp,'Resultado estimado',m.estimatedProfit,m.missingCosts?'Hay costos incompletos':'Ventas menos costos y gastos','lavender']].map(([Icon,label,value,hint,tone])=><article className="command-metric" key={label}><div><span className={`command-icon ${tone}`}><Icon size={19}/></span><span>{label}</span></div><strong>{money(value)}</strong><p className={label==='Resultado estimado'&&m.missingCosts?'metric-warning':''}>{hint}</p></article>)}</div>
 {m.undatedCollections>0&&<p className="ce-info">Hay {money(m.undatedCollections)} de cobros históricos sin fecha. Se conservan en el saldo pagado, pero no se asignan a este período.</p>}
 </section>
 {ui.showQuickActions!==false&&<section className="home-section home-actions" aria-labelledby="home-actions-title"><div className="home-section-heading"><div><span className="ce-eyebrow">02 · ACCESOS RÁPIDOS</span><h3 id="home-actions-title">¿Qué necesitas hacer?</h3></div><p>Un acceso directo a tus tareas habituales.</p></div><div className="command-shortcuts">{ui.shortcuts.map(id=>{const Icon=icons[id]||Plus;return <button key={id} onClick={()=>goTo(id)}><Icon size={17}/>{SHORTCUTS.find(x=>x.id===id).name}<ArrowUpRight size={14}/></button>})}<button className="shortcut-edit" aria-label="Personalizar accesos rápidos" onClick={onPersonalize}><SlidersHorizontal size={17}/></button></div></section>}
 <section className="home-section home-followup" aria-labelledby="home-followup-title"><div className="home-section-heading"><div><span className="ce-eyebrow">03 · SEGUIMIENTO</span><h3 id="home-followup-title">Tu día a día, por partes.</h3></div><p>Actividad, entregas y objetivos en sus propios espacios.</p></div><div className={`command-widgets layout-${ui.dashboardLayout}`}>{ui.widgetOrder.filter(id=>!ui.hiddenWidgets.includes(id)).map(id=><div key={id} data-widget={id}>{cards[id]}</div>)}</div>
 {ui.hiddenWidgets.length===WIDGETS.length&&<button className="command-restore-widgets" onClick={onPersonalize}><PanelsPlaceholder/>Tu inicio, despejado. Elige las tarjetas que quieras volver a ver.<ArrowRight size={17}/></button>}
 </section>
 <p className="command-footnote">Los resultados dependen de tus registros y costos. El dinero cobrado y el saldo por cobrar representan movimientos distintos. <button onClick={()=>goTo('informes')}>Entender mis números <ArrowUpRight size={12}/></button></p></div>;
}
function PanelsPlaceholder(){return <BarChart3 size={20}/>;}
