import React,{useState} from 'react';
import {Palette,PanelsTopLeft,Building2,Check,ArrowUp,ArrowDown,Upload,RotateCcw,Sun,Moon,Monitor,Plus,Sparkles,LayoutDashboard,ArrowRight,ImagePlus} from 'lucide-react';
import {AccessibleDialog,useDraftGuard} from './WorkspaceFeatures.jsx';
import {PALETTES,WIDGETS,SHORTCUTS,DEFAULT_APPEARANCE,normalizeAppearance,appearanceTokens,initials} from '../domain/appearance.js';

export function WorkspaceMark({settings,profile,className=''}){return <span className={`studio-mark ${className}`}>{settings.workspaceLogo?<img src={settings.workspaceLogo} alt="Tu logo personalizado"/>:<span>{initials(settings.workspaceName||profile.name)}</span>}</span>;}
async function readLogo(file){
 if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('Elige una imagen PNG, JPG o WebP.');
 if(file.size>2*1024*1024)throw new Error('Tu imagen debe pesar menos de 2 MB.');
 const bitmap=await createImageBitmap(file);try{if(!bitmap.width||!bitmap.height||bitmap.width*bitmap.height>40000000)throw new Error('La imagen es demasiado grande.');const scale=Math.min(1,256/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);const result=canvas.toDataURL('image/webp',.85);if(result.length>=200000)throw new Error('No se pudo reducir el logo. Prueba una imagen más simple.');return result;}finally{bitmap.close();}
}
export default function PersonalizeStudio({settings,profile,onApply,onClose,systemDark}){
 const [draft,setDraft]=useState(()=>normalizeAppearance(settings)),[tab,setTab]=useState('style'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const dirty=JSON.stringify(draft)!==JSON.stringify(normalizeAppearance(settings));useDraftGuard(dirty);
 const change=patch=>{setDraft(d=>normalizeAppearance({...d,...patch}));setError('');};
 const close=()=>{if(!dirty||window.confirm('¿Cerrar sin aplicar los cambios de tu espacio?'))onClose();};
 const dark=draft.theme==='dark'||draft.theme==='system'&&systemDark;
 async function logo(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);try{change({workspaceLogo:await readLogo(file)});}catch(e){setError(e.message);}finally{setBusy(false);}}
 function move(id,delta){const order=[...draft.widgetOrder],i=order.indexOf(id);[order[i],order[i+delta]]=[order[i+delta],order[i]];change({widgetOrder:order});}
 function shortcut(id){const exists=draft.shortcuts.includes(id);if(exists&&draft.shortcuts.length===1){setError('Conserva al menos un acceso rápido.');return;}if(!exists&&draft.shortcuts.length===4){setError('Puedes fijar cuatro accesos. Quita uno para elegir otro.');return;}change({shortcuts:exists?draft.shortcuts.filter(x=>x!==id):[...draft.shortcuts,id]});}
 return <AccessibleDialog title="Hazlo tuyo" onClose={close} wide><div className="studio-intro"><span className="ce-eyebrow">TU NEGOCIO. TU ESTILO.</span><p>Un espacio que se sienta tan tuyo como lo que estás construyendo.</p></div><div className="studio-body"><div className="studio-controls"><div className="studio-tabs" role="tablist" aria-label="Opciones de personalización">{[['style','Estilo',Palette],['identity','Identidad',Building2],['dashboard','Mi inicio',PanelsTopLeft]].map(([id,name,Icon])=><button type="button" key={id} role="tab" tabIndex={tab===id?0:-1} onKeyDown={e=>{const ids=['style','identity','dashboard'];let next;if(e.key==='ArrowRight')next=ids[(ids.indexOf(id)+1)%3];else if(e.key==='ArrowLeft')next=ids[(ids.indexOf(id)+2)%3];else if(e.key==='Home')next=ids[0];else if(e.key==='End')next=ids[2];if(next){e.preventDefault();setTab(next);document.getElementById(`studio-tab-${next}`)?.focus();}}} aria-selected={tab===id} aria-controls={`studio-${id}`} id={`studio-tab-${id}`} onClick={()=>setTab(id)}><Icon size={16}/>{name}</button>)}</div>
 {tab==='style'&&<section role="tabpanel" aria-labelledby="studio-tab-style" id="studio-style"><h3>Elige tus colores</h3><p className="studio-hint">Elige una paleta o usa el color de tu marca.</p><div className="studio-palettes">{PALETTES.map(p=><button type="button" aria-label={`Paleta ${p.name}`} aria-pressed={draft.palette===p.id&&!draft.customAccent} className="studio-palette" key={p.id} onClick={()=>change({palette:p.id,customAccent:''})}><span className="studio-swatches"><i style={{background:'#0f172a'}}/><i style={{background:p.accent}}/><i style={{background:`${p.accent}25`}}/>{draft.palette===p.id&&!draft.customAccent&&<Check size={16}/>}</span><strong>{p.name}</strong><small>{p.description}</small></button>)}</div><label className="studio-color"><span><strong>O usa tu propio color</strong><small>Adaptamos el contraste del texto automáticamente.</small></span><input aria-label="Color personalizado" type="color" value={draft.customAccent||PALETTES.find(p=>p.id===draft.palette).accent} onChange={e=>change({customAccent:e.target.value})}/></label><h3>Modo de apariencia</h3><div className="studio-options">{[['light','Claro',Sun],['dark','Oscuro',Moon],['system','Sistema',Monitor]].map(([value,label,Icon])=><button type="button" aria-pressed={draft.theme===value} key={value} onClick={()=>change({theme:value})}><Icon size={18}/>{label}</button>)}</div><div className="studio-fields"><label>Espaciado<select aria-label="Espaciado" value={draft.density} onChange={e=>change({density:e.target.value})}><option value="comfortable">Cómodo</option><option value="compact">Compacto</option></select></label><label>Tamaño del texto<select aria-label="Tamaño del texto" value={draft.textSize} onChange={e=>change({textSize:e.target.value})}><option value="normal">Estándar</option><option value="large">Más grande</option></select></label></div><label className="studio-check"><input type="checkbox" checked={draft.reduceMotion} onChange={e=>change({reduceMotion:e.target.checked})}/>Reducir animaciones</label></section>}
 {tab==='identity'&&<section role="tabpanel" aria-labelledby="studio-tab-identity" id="studio-identity"><h3>Tu nombre, tu logo, tu estilo</h3><p className="studio-hint">Personaliza tu vista. El nombre en comprobantes se mantiene en «Mi negocio».</p><div className="studio-logo-editor"><WorkspaceMark settings={draft} profile={profile}/><div><label className="studio-upload"><ImagePlus size={17}/>{busy?'Preparando…':'Elegir mi logo'}<input aria-label="Subir logo" type="file" accept="image/png,image/jpeg,image/webp" onChange={logo} disabled={busy}/></label><small>PNG, JPG o WebP · hasta 2 MB</small>{draft.workspaceLogo&&<button type="button" className="ce-text-button" onClick={()=>change({workspaceLogo:''})}>Usar iniciales</button>}</div></div><div className="studio-fields single"><label>Nombre de mi espacio<input aria-label="Nombre de mi espacio" value={draft.workspaceName} onChange={e=>change({workspaceName:e.target.value})} maxLength={60} placeholder={profile.name}/></label><label>Frase de bienvenida<textarea aria-label="Frase de mi espacio" value={draft.workspaceMotto} onChange={e=>change({workspaceMotto:e.target.value})} maxLength={110} rows={3}/><small>{draft.workspaceMotto.length}/110</small></label></div><p className="studio-local-note">Tu logo y estas preferencias se guardan en este {import.meta.env.VITE_DESKTOP === 'true' ? 'PC' : 'navegador'}, para tu usuario y este negocio. Cada integrante puede crear su propia vista.</p></section>}
 {tab==='dashboard'&&<section role="tabpanel" aria-labelledby="studio-tab-dashboard" id="studio-dashboard"><h3>Lo importante, a tu manera</h3><div className="studio-options layouts">{[['panorama','Panorama','Todo de un vistazo'],['focus','Enfoque','Tarjetas en una columna']].map(([id,name,desc])=><button type="button" key={id} aria-pressed={draft.dashboardLayout===id} onClick={()=>change({dashboardLayout:id})}><span className={`layout-diagram ${id}`} aria-hidden="true"><i/><i/><i/><i/></span><strong>{name}</strong><small>{desc}</small></button>)}</div><h3>Elige y ordena tus tarjetas</h3><p className="studio-hint">Los números principales siempre quedan a la vista.</p><div className="studio-widget-list">{draft.widgetOrder.map((id,i)=>{const widget=WIDGETS.find(x=>x.id===id);return <div key={id}><label><input type="checkbox" aria-label={`Mostrar ${widget.name}`} checked={!draft.hiddenWidgets.includes(id)} onChange={e=>change({hiddenWidgets:e.target.checked?draft.hiddenWidgets.filter(x=>x!==id):[...draft.hiddenWidgets,id]})}/><span><strong>{widget.name}</strong><small>{widget.description}</small></span></label><div><button type="button" aria-label={`Subir ${widget.name}`} disabled={i===0} onClick={()=>move(id,-1)}><ArrowUp size={16}/></button><button type="button" aria-label={`Bajar ${widget.name}`} disabled={i===draft.widgetOrder.length-1} onClick={()=>move(id,1)}><ArrowDown size={16}/></button></div></div>})}</div><h3>Mis accesos rápidos <small>{draft.shortcuts.length}/4</small></h3><div className="studio-shortcuts">{SHORTCUTS.map(s=><button type="button" key={s.id} aria-pressed={draft.shortcuts.includes(s.id)} onClick={()=>shortcut(s.id)}>{draft.shortcuts.includes(s.id)?<Check size={14}/>:<Plus size={14}/>} {s.name}</button>)}</div></section>}
 </div><aside className="studio-preview-column"><span className="ce-eyebrow">ASÍ SE VERÁ TU ESPACIO</span><div className={`studio-preview ${dark?'preview-dark':''}`} style={appearanceTokens(draft,dark)}><div className="preview-sidebar"><LayoutDashboard size={19}/>{[1,2,3,4,5].map(i=><i key={i}/>)}</div><div className="preview-main"><div className="preview-brand"><WorkspaceMark settings={draft} profile={profile}/><strong>{draft.workspaceName||profile.name}</strong></div><div className="preview-greeting"><span>TU CENTRO DE CONTROL</span><h4>Tu próxima gran<br/>decisión empieza aquí.</h4><p>{draft.workspaceMotto||'Cada decisión cuenta.'}</p><span className="preview-cta">Nueva venta <Plus size={12}/></span></div><div className="preview-metrics"><div>Ventas<strong>•••••</strong></div><div>Cobrado<strong>•••••</strong></div></div><div className={`preview-widgets ${draft.dashboardLayout}`}>{draft.widgetOrder.filter(id=>!draft.hiddenWidgets.includes(id)).map((id,i)=><div key={id}><span>{WIDGETS.find(w=>w.id===id).name}</span>{id==='activity'?<div className="preview-bars">{[35,58,44,76,60,90,68].map((v,i)=><i key={i} style={{height:v+'%'}}/>)}</div>:<><i/><i/></>}</div>)}</div></div></div><p className="studio-hint">Vista previa ilustrativa. Los cambios se aplican al guardarlos.</p><div className="studio-personal-note"><Sparkles size={19}/><p>El orden lo eliges tú.<br/><strong>Tu información sigue en su lugar.</strong></p></div></aside></div>
 {error&&<p role="alert" className="ce-error">{error}</p>}<footer className="studio-footer"><button type="button" className="studio-reset" onClick={()=>change(DEFAULT_APPEARANCE)}><RotateCcw size={15}/>Restablecer estilo</button><span>{import.meta.env.VITE_DESKTOP === 'true' ? 'Guardado en este PC y negocio' : 'Guardado en este navegador y negocio'}</span><button type="button" className="ce-button ce-button-secondary" onClick={close}>Cancelar</button><button type="button" className="ce-button" disabled={busy} onClick={()=>{try{if(onApply(draft)!==false)onClose();else setError('No se guardó la personalización. Revisa el espacio disponible del navegador.');}catch(e){setError(e.message);}}}>Aplicar mi estilo <ArrowRight size={16}/></button></footer></AccessibleDialog>;
}
