import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {generateKeyPairSync,sign} from 'node:crypto';
import {createRequire} from 'node:module';
const {createLicenseClient,decodeLease,validateConfig,checkoutAllowed}=createRequire(import.meta.url)('../desktop/license-client.cjs');
const DAY=86400000,deviceId='a'.repeat(64),keys=generateKeyPairSync('ed25519');
const config={server:'https://example.com',mode:'test',publicKey:keys.publicKey.export({format:'jwk'})};
const safeStorage={isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s),decryptString:b=>b.toString()};
function token(c,key=keys.privateKey){const h=Buffer.from(JSON.stringify({alg:'EdDSA',typ:'JWT'})).toString('base64url'),p=Buffer.from(JSON.stringify(c)).toString('base64url');return h+'.'+p+'.'+sign(null,Buffer.from(h+'.'+p),key).toString('base64url');}
async function fixture(t){const dir=await mkdtemp(join(tmpdir(),'ce-license-unit-'));t.after(()=>rm(dir,{recursive:true,force:true}));let now=Date.UTC(2026,9,8),mono=0,offline=false,paid=false,bad=false;const start=now,calls=[];
const options={dir,config,safeStorage,getDeviceId:async()=>deviceId,clock:()=>now,monotonic:()=>mono,fetcher:async(url,req)=>{calls.push({url,req});if(offline)throw Error('fetch failed');if(url.endsWith('/checkout'))return Response.json({url:'https://sandbox.mercadopago.cl/checkout/v1/redirect?pref_id=test',mode:'test'});const trialEndsAt=start+15*DAY,paidUntil=paid?trialEndsAt+30*DAY:null,writeUntil=paidUntil||trialEndsAt,canWrite=now<writeUntil;const serverNow=start+mono;const c={iss:'control-emprende-licenses',aud:'control-emprende-desktop',v:1,licenseId:'one',deviceId,mode:'test',iat:Math.floor(serverNow/1000),exp:Math.floor(serverNow/1000)+7*86400,status:canWrite?(paid?'active':'trial'):'read_only',canWrite,trialEndsAt,paidUntil,writeUntil};return Response.json({lease:token(c,bad?generateKeyPairSync('ed25519').privateKey:keys.privateKey),billingEnabled:true});}};
return {dir,calls,options,client:createLicenseClient(options),advance:n=>{now+=n;mono+=n;},rollback:n=>now-=n,offline:()=>offline=true,online:()=>offline=false,pay:()=>paid=true,bad:()=>bad=true};}
test('enroll once, store secret, restart keeps trial and never exposes credentials',async t=>{const f=await fixture(t);const first=await f.client.refresh();assert.equal(first.status,'trial');assert.equal(first.daysRemaining,15);assert.equal(first.secret,undefined);const stored=JSON.parse(await readFile(join(f.dir,'license-v1.enc'),'utf8'));assert.match(stored.secret,/^[a-f0-9]{64}$/);f.advance(DAY);const again=createLicenseClient(f.options);assert.equal((await again.refresh()).daysRemaining,14);assert.equal(f.calls[1].url,'https://example.com/status');assert.equal(f.calls[1].req.headers.Authorization,'Bearer '+stored.secret);});
test('offline receipt allows writes for seven days, then only read and export',async t=>{const f=await fixture(t);await f.client.refresh();f.offline();f.advance(6*DAY);assert.equal((await f.client.authorizeWrite()).canWrite,true);f.advance(2*DAY);const s=await f.client.authorizeWrite();assert.equal(s.canWrite,false);assert.equal(s.canRead,true);assert.equal(s.canExport,true);});
test('trial expires and payment confirmation restores thirty days; checkout alone does not',async t=>{const f=await fixture(t);await f.client.refresh();f.advance(16*DAY);assert.equal((await f.client.refresh()).canWrite,false);await f.client.checkout();assert.equal((await f.client.status()).canWrite,false);f.pay();assert.equal((await f.client.refresh()).status,'active');});
test('clock rollback cannot revive access after restart',async t=>{const f=await fixture(t);await f.client.refresh();f.advance(2*DAY);await f.client.authorizeWrite();f.rollback(DAY);f.offline();assert.equal((await createLicenseClient(f.options).authorizeWrite()).canWrite,false);});
test('invalid signature cannot replace existing authorization',async t=>{const f=await fixture(t);await f.client.refresh();f.bad();f.advance(8*DAY);const s=await f.client.refresh();assert.equal(s.canWrite,false);assert.match(s.error,/firma/);});
test('corrupt activation is not replaced with new trial',async t=>{const f=await fixture(t);await writeFile(join(f.dir,'license-v1.enc'),'corrupt');assert.equal((await f.client.refresh()).canWrite,false);assert.equal(f.calls.length,0);assert.equal(await readFile(join(f.dir,'license-v1.enc'),'utf8'),'corrupt');});
test('storage encryption failure refuses writes',async t=>{const f=await fixture(t);await f.client.refresh();f.options.safeStorage={...safeStorage,isEncryptionAvailable:()=>false};assert.equal((await createLicenseClient(f.options).authorizeWrite()).canWrite,false);});
test('receipt from another device or mode rejected',async t=>{const f=await fixture(t);await f.client.refresh();const receipt=JSON.parse(await readFile(join(f.dir,'license-v1.enc'),'utf8')).lease;assert.throws(()=>decodeLease(receipt,validateConfig(config),'b'.repeat(64)));assert.throws(()=>decodeLease(receipt,validateConfig({...config,mode:'production'}),deviceId));});
test('checkout restricts protocol, credentials and exact host',()=>{assert(checkoutAllowed('https://sandbox.mercadopago.cl/checkout/v1/redirect?pref_id=1'));for(const s of ['https://mercadopago.cl.evil.com/checkout/','https://user@www.mercadopago.cl/checkout/','http://www.mercadopago.cl/checkout/','https://www.mercadopago.cl/other'])assert.equal(checkoutAllowed(s),false);});

test('correcting an accidentally advanced clock recovers after a verified server refresh',async t=>{const f=await fixture(t);await f.client.refresh();f.rollback(-20*DAY);assert.equal((await f.client.authorizeWrite()).canWrite,false);f.rollback(20*DAY);assert.equal((await f.client.status()).canWrite,false);assert.equal((await f.client.refresh()).canWrite,true);});
